

const initialState = {
  userCuti:[
    {
    userId:1,
    userNama:"Jono Sujono",
    cutiId:1,
    tanggalPengajuan:"12-12-2020",
    tanggalBerakhir:"15-12-2020",
    statusPengajuan:"Menunggu Konfirmasi HRD",
    alasan:"Sakit",
  },
  {
    userId:1,
    userNama:"Jono Sujono",
    cutiId:2,
    tanggalPengajuan:"12-12-2020",
    tanggalBerakhir:"30-12-2020",
    statusPengajuan:"Menunggu Konfirmasi HRD",
    alasan:"Menikah",
  },
  {
    userId:5,
    userNama:"Ismail bin Mail",
    cutiId:3,
    tanggalPengajuan:"12-12-2020",
    tanggalBerakhir:"20-12-2020",
    statusPengajuan:"Menunggu Konfirmasi HRD",
    alasan:"Menikah ",
  }
]
,
    dataKaryawan: [
      [
        {
          "id": 1,
          "nik": "20201005",
          "jabatan": "Aplication Owner",
          "noktp": "3275101010102020",
          "nama": "Jono Sujono",
          "email": "jonosujono@mail.btpns.com",
          "password": "123mantap",
          "tglLahir": "20 mei 1997",
          "tempatLahir": "jakarta",
          "alamat": "bintara, bekasi barat",
          "notelp": "082120201010",
          "pendidikanTerkahir": "S1 Sistem Informasi",
          "institusiPendidikan": "Institut 20 November",
          "statusPernikahan": "Lajang",
          "roleType": 0
        },
        {
          "id": 2,
          "nik": "20201002",
          "jabatan": "Aplication Owner",
          "noktp": "3575202020201010",
          "nama": "James Bond",
          "email": "jamesbond@mail.btpns.com",
          "password": "agentbond007",
          "tglLahir": "8 april 1976",
          "tempatLahir": "jakarta",
          "alamat": "menteng, jakarta pusat",
          "notelp": "088833333007",
          "pendidikanTerkahir": "S1 Sistem Informasi",
          "institusiPendidikan": "Institut Teknologi Bekasi",
          "statusPernikahan": "Lajang",
          "roleType": 0
        },
        {
          "id": 3,
          "nik": "20201001",
          "jabatan": "HC Lead",
          "noktp": "3622129755612929",
          "nama": "Nissa Sabyan",
          "email": "nissa_imutz@mail.btpns.com",
          "password": "nissacantik",
          "tglLahir": "5 juli 1999",
          "tempatLahir": "jakarta",
          "alamat": "ciputat, tangerang ",
          "notelp": "087783899565",
          "pendidikanTerkahir": "S1 Psikologi",
          "institusiPendidikan": "Universitas Negeri Syarif Hidayatulah",
          "statusPernikahan": "Menikah",
          "roleType": 1
        },
        {
          "id": 4,
          "nik": "20201003",
          "jabatan": "Aplication Owner",
          "noktp": "3472199779916666",
          "nama": "Naruto Uzumaki",
          "email": "hokage6@mail.btpns.com",
          "password": "konohagakure",
          "tglLahir": "31 juni 1988",
          "tempatLahir": "jakarta",
          "alamat": "padalarang, bandung",
          "notelp": "082177881818",
          "pendidikanTerkahir": "S1 Teknik Informatika",
          "institusiPendidikan": "Universitas Negeri Api",
          "statusPernikahan": "Menikah",
          "roleType": 0
        },
        {
          "id": 5,
          "nik": "20201004",
          "jabatan": "IT PMO",
          "noktp": "3356199574913641",
          "nama": "Ismail bin Mail",
          "email": "mail_ismail@mail.btpns.com",
          "password": "ayamgoreng2ringgit",
          "tglLahir": "31 Agustus 1998",
          "tempatLahir": "Kuala Lumpur",
          "alamat": "setiabudi, bandung",
          "notelp": "082232557622",
          "pendidikanTerkahir": "S1 Teknik Informatika",
          "institusiPendidikan": "Universitas Negeri Malaysia",
          "statusPernikahan": "Lajang",
          "roleType": 2
        },
        {
          "id": 6,
          "nik": "20201026",
          "jabatan": "Software Engineer",
          "noktp": "3322199874923336",
          "nama": "Jarjit Singh",
          "email": "jarjit@mail.btpns.com",
          "password": "rajapantun",
          "tglLahir": "20 Agustus 1999",
          "tempatLahir": "Kuala Lumpur",
          "alamat": "setiabudi, bandung",
          "notelp": "082232557622",
          "pendidikanTerkahir": "S1 Teknik Informatika",
          "institusiPendidikan": "Universitas Negeri Malaysia",
          "statusPernikahan": "Lajang",
          "roleType": 0
        },
        {
          "id": 7,
          "nik": "20201027",
          "jabatan": "Front-End Developer",
          "noktp": "3467789500913622",
          "nama": "Upin",
          "email": "upin@mail.btpns.com",
          "password": "upinipin",
          "tglLahir": "31 Juni 2000",
          "tempatLahir": "Kuala Lumpur",
          "alamat": "setiabudi, bandung",
          "notelp": "082332447623",
          "pendidikanTerkahir": "S1 Teknik Informatika",
          "institusiPendidikan": "Universitas Negeri Malaysia",
          "statusPernikahan": "Lajang",
          "roleType": 0
        },
        {
          "id": 8,
          "nik": "20201028",
          "jabatan": "Back-End Developer",
          "noktp": "3467789500913623",
          "nama": "Ipin",
          "email": "ipin@mail.btpns.com",
          "password": "upinipin",
          "tglLahir": "31 Juni 2000",
          "tempatLahir": "Kuala Lumpur",
          "alamat": "setiabudi, bandung",
          "notelp": "08223233765",
          "pendidikanTerkahir": "S1 Teknik Informatika",
          "institusiPendidikan": "Universitas Negeri Malaysia",
          "statusPernikahan": "Lajang",
          "roleType": 0
        },
        {
          "id": 9,
          "nik": "20201029",
          "jabatan": "CEO",
          "noktp": "3776199874913677",
          "nama": "Ehsan",
          "email": "ehsan@mail.btpns.com",
          "password": "intanpayo",
          "tglLahir": "3 April 1999",
          "tempatLahir": "Kuala Lumpur",
          "alamat": "setiabudi, bandung",
          "notelp": "08111777555",
          "pendidikanTerkahir": "S1 Teknik Informatika",
          "institusiPendidikan": "Universitas Negeri Malaysia",
          "statusPernikahan": "Lajang",
          "roleType": 2
        },
        {
          "id": 10,
          "nik": "20201020",
          "jabatan": "Head of IT Team",
          "noktp": "3756123154776655",
          "nama": "Fizi",
          "email": "fizi@mail.btpns.com",
          "password": "anakbuahehsan",
          "tglLahir": "13 Desember 1998",
          "tempatLahir": "Kuala Lumpur",
          "alamat": "setiabudi, bandung",
          "notelp": "0822333555666",
          "pendidikanTerkahir": "S1 Teknik Informatika",
          "institusiPendidikan": "Universitas Negeri Malaysia",
          "statusPernikahan": "Lajang",
          "roleType": 2
        },
        {
          "id": 11,
          "nik": "20201021",
          "jabatan": "UI/UX Designer",
          "noktp": "37561639575544633",
          "nama": "MeyMey",
          "email": "meymey@mail.btpns.com",
          "password": "sayasuka",
          "tglLahir": "22 Oktober 1998",
          "tempatLahir": "Kuala Lumpur",
          "alamat": "menteng, jakarta",
          "notelp": "082132777666",
          "pendidikanTerkahir": "S1 Teknik Informatika",
          "institusiPendidikan": "Universitas Negeri Malaysia",
          "statusPernikahan": "Lajang",
          "roleType": 0
        },
        {
          "id": 12,
          "nik": "20201022",
          "jabatan": "Database Engineer",
          "noktp": "37661199874912765",
          "nama": "Susanti",
          "email": "sisusanti@mail.btpns.com",
          "password": "sayacantik",
          "tglLahir": "17 Agustus 1998",
          "tempatLahir": "Bandung",
          "alamat": "cikini, jakarta",
          "notelp": "081276541234",
          "pendidikanTerkahir": "S1 Teknik Informatika",
          "institusiPendidikan": "Universitas Indonesia",
          "statusPernikahan": "Lajang",
          "roleType": 0
        },
        {
          "id": 13,
          "nik": "20111023",
          "jabatan": "HC/HR Head",
          "noktp": "3766229873242777",
          "nama": "Ros",
          "email": "kak_ros@mail.btpns.com",
          "password": "roscantik",
          "tglLahir": "4 Maret 1980",
          "tempatLahir": "Kuala Lumpur",
          "alamat": "kuala lumpur, kuala lumpur ",
          "notelp": "081276541234",
          "pendidikanTerkahir": "S2 Magister Psikologi",
          "institusiPendidikan": "Universitas Negeri Malaysia",
          "statusPernikahan": "Lajang",
          "roleType": 1
        }
      ],
      ]
}
const Cuti = (state = initialState, action) => {
    switch (action.type) {
        case "cuti":
            return {
                ...state,
                Cuti : action.payload
            }
        default:
            return state
    }
}

export default Cuti 